### PR TITLE
Added splitter exec

### PR DESCRIPTION
**Pull request by jackwilliamson**

### CODE REVIEW

**Review by Ercadio — APPROVED** [review]

**Comment by Ercadio** [comment]
oh we will need to import them from pipeline tho. Can you also import the new CSV executor?

**Comment by jackwilliamson** [comment]
@Ercadio will do

**Review by tonymeng1 — APPROVED** [review]

**Comment by tonymeng1** [comment]
Should this go into default_configuration.yml as well?

**Comment by jackwilliamson** [comment]
@tonymeng1 ya the second commit fixes that

**Comment by tonymeng1** [comment]
Woops. Don't know how I missed that..

**Pull request merged**
